apiVersion: v1
kind: Service
metadata:
  name: authful-web-service
spec:
  selector:
    app: authful-web
  ports:
  - protocol: "TCP"
    port: 3030
    targetPort: 8080
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: authful-web
spec:
  selector:
    matchLabels:
      app: authful-web
  replicas: 5
  template:
    metadata:
      labels:
        app: authful-web
    spec:
      containers:
      - name: authful-web
        image: authful-web
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000