apiVersion: apps/v1
kind: Deployment
metadata:
  name: authful-developers-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authful-developers-db-template
  template:
    metadata:
      labels:
        app: authful-developers-db-template
    spec:
      containers:
      - args:
        - mysqld
        - --innodb_file_per_table
        env:
        - name: MYSQL_DATABASE
          value: authful_developers
        - name: MYSQL_HOST
          value: authful-developers-db
        - name: MYSQL_PASSWORD
          value: 8FUb9bqVTtLyU2i8
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD
          value: 6oK84adtaaxBRuKV
        - name: MYSQL_USER
          value: dev_admin
        image: mysql/mysql-server
        imagePullPolicy: ""
        name: authful-developers-db
        ports:
        - containerPort: 3306
      restartPolicy: Always
      volumes: null

---
apiVersion: v1
kind: Service
metadata:
  name: authful-developers-db
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: authful-developers-db-template





---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authful-users-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authful-users-db-template
  template:
    metadata:
      labels:
        app: authful-users-db-template
    spec:
      containers:
      - args:
        - mysqld
        - --innodb_file_per_table
        env:
        - name: MYSQL_DATABASE
          value: authful_users
        - name: MYSQL_HOST
          value: authful-users-db
        - name: MYSQL_PASSWORD
          value: 8t97tP366iPf7HnC
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD
          value: 80jqn1uAWnoTjfPw
        - name: MYSQL_USER
          value: users_admin
        image: mysql/mysql-server
        imagePullPolicy: ""
        name: authful-users-db
        ports:
        - containerPort: 3306
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
---
apiVersion: v1
kind: Service
metadata:
  name: authful-users-db
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: authful-users-db-template




---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authful-developers-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authful-developers-template
  template:
    metadata:
      labels:
        app: authful-developers-template
    spec:
      containers:
      - env:
        - name: AUTHFUL_LOG_LEVEL
          value: VERBOSE
        - name: CORS_ALLOWED_HEADERS
          value: Accept,Cache,Content-Type,Authorize,Access-Control-Allow-Origin,X-Requested-With,X-Auth-Token,Content-Length,Accept-Encoding,X-CSRF-Token,Authorization,x-trace-id
        - name: CORS_ALLOWED_METHODS
          value: GET,HEAD,POST,PUT,PATCH,OPTIONS
        - name: CORS_ORIGIN_ALLOWED
          value: http://localhost:8080, http://localhost:3000
        - name: DATABASE_SERVER_DATABASE
          value: authful_developers
        - name: DATABASE_SERVER_HOST
          value: authful-developers-db
        - name: DATABASE_SERVER_PASSWORD
          value: 8FUb9bqVTtLyU2i8
        - name: DATABASE_SERVER_PORT
          value: "3306"
        - name: DATABASE_SERVER_USERNAME
          value: dev_admin
        - name: SECURITY_JWT_KEY
          value: JI1PmZvvwLfKPSR97DHogdoA6ahWPBUyr3YaaVgCMm3XGhlF8s306UgJV0YDNx
        - name: SECURITY_PASSWORD_COST_FACTOR
          value: "14"
        - name: SERVICE_ADDRESS
          value: http://authful-developers:8080
        - name: WEB_SERVER_PORT
          value: "8080"
        image: highfiveboom/authful-developers:latest
        imagePullPolicy: ""
        name: authful-developers
        ports:
        - containerPort: 8080        
      restartPolicy: Always

--- 
apiVersion: v1
kind: Service
metadata:
  name: authful-developers
spec:
  type: ClusterIP
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: authful-developers-template

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authful-users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authful-users-template
  template:
    metadata:
       labels:
        app: authful-users-template
    spec:
      containers:
      - env:
        - name: AUTHFUL_LOG_LEVEL
          value: VERBOSE
        - name: CORS_ALLOWED_HEADERS
          value: Accept,Cache,Content-Type,Authorize,Access-Control-Allow-Origin,X-Requested-With,X-Auth-Token,Content-Length,Accept-Encoding,X-CSRF-Token,Authorization,x-trace-id
        - name: CORS_ALLOWED_METHODS
          value: GET,HEAD,POST,PUT,PATCH,OPTIONS
        - name: CORS_ORIGIN_ALLOWED
          value: http://localhost:8080, http://localhost:3000
        - name: DATABASE_SERVER_DATABASE
          value: authful_users
        - name: DATABASE_SERVER_HOST
          value: authful-users-db
        - name: DATABASE_SERVER_PASSWORD
          value: 8t97tP366iPf7HnC
        - name: DATABASE_SERVER_PORT
          value: "3306"
        - name: DATABASE_SERVER_USERNAME
          value: users_admin
        - name: SECURITY_JWT_KEY
          value: JI1PmZvvwLfKPSR97DHogdoA6ahWPBUyr3YaaVgCMm3XGhlF8s306UgJV0YDNx
        - name: SECURITY_PASSWORD_COST_FACTOR
          value: "14"
        - name: SERVICE_ADDRESS
          value: http://authful-users:8080
        - name: WEB_SERVER_PORT
          value: "8080"
        image: highfiveboom/authful-users:latest
        imagePullPolicy: ""
        name: authful-users
        ports:
        - containerPort: 8080
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
---
apiVersion: v1
kind: Service
metadata:
  name: authful-users
spec:
  type: ClusterIP
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: authful-users-template
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authful-proxy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authful-proxy-template
  template:
    metadata:
      labels:
        app: authful-proxy-template
    spec:
      containers:
      - env:
        - name: AUTHFUL_LOG_LEVEL
          value: VERBOSE
        - name: CORS_ALLOWED_HEADERS
          value: Accept,Cache,Content-Type,Authorize,Access-Control-Allow-Origin,X-Requested-With,X-Auth-Token,Content-Length,Accept-Encoding,X-CSRF-Token,Authorization,x-trace-id
        - name: CORS_ALLOWED_METHODS
          value: GET,HEAD,POST,PUT,PATCH,OPTIONS
        - name: CORS_ORIGIN_ALLOWED
          value: http://localhost:8080, http://localhost:3000
        - name: PROVIDERS_DEVELOPER_SERVER_URI
          value: http://authful-developers:8080
        - name: PROVIDERS_USER_SERVER_URI
          value: http://authful-users:8080
        - name: SECURITY_JWT_KEY
          value: JI1PmZvvwLfKPSR97DHogdoA6ahWPBUyr3YaaVgCMm3XGhlF8s306UgJV0YDNx
        - name: SECURITY_PASSWORD_COST_FACTOR
          value: "14"
        - name: WEB_SERVER_PORT
          value: "8080"
        image: highfiveboom/authful-proxy:latest
        imagePullPolicy: ""
        name: authful-proxy
        ports:
        - containerPort: 8080
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
---
apiVersion: v1
kind: Service
metadata:
  name: authful-proxy
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30100   
  selector:
    app: authful-proxy-template

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authful-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authful-web-template
  template:
    metadata:
      labels:
        app: authful-web-template
    spec:
      containers:
      - env:
        - name: AUTHFUL_LOG_LEVEL
          value: VERBOSE
        - name: SERVICE_ADDRESS
          value: http://authful-web:8080
        - name: WEB_SERVER_PORT
          value: "8080"
        image: highfiveboom/authful-web:latest
        imagePullPolicy: ""
        name: authful-web
        ports:
        - containerPort: 8080
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
---
apiVersion: v1
kind: Service
metadata:
  name: authful-web
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000    
  selector:
    app: authful-web-template
---