version: '3.4'

x-jwt-key: &security_jwt_key
  SECURITY_JWT_KEY: JI1PmZvvwLfKPSR97DHogdoA6ahWPBUyr3YaaVgCMm3XGhlF8s306UgJV0YDNx     

x-security-password-factor: &security_password_factor
  SECURITY_PASSWORD_COST_FACTOR: 14

x-is-debug: &is_debug 1
  
x-users-db-username: &usersdbusername users_db_admin
services:
  developers_db:
    image: mysql
    #command: --default-authentication-plugin=mysql_native_password
    restart: always  
    volumes:
      - ./db/authful_developers:/docker-entrypoint-initdb.d
    environment: 
      MYSQL_HOST: &db_dev_host developers_db
      MYSQL_PORT: &db_dev_port 3306
      MYSQL_DATABASE: &db_dev_database authful_developers
      MYSQL_ROOT_PASSWORD: &db_dev_root_password 6oK84adtaaxBRuKV
      MYSQL_USER: &db_dev_user dev_admin
      MYSQL_PASSWORD: &db_dev_password 8FUb9bqVTtLyU2i8      
    ports:
      - 33062:3306
    command: mysqld --innodb_file_per_table
  users_db:
    image: mysql
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db/authful_users:/docker-entrypoint-initdb.d
    environment: 
      MYSQL_HOST: &db_users_host users_db
      MYSQL_PORT: &db_users_port 3306
      MYSQL_DATABASE: &db_users_database authful_users
      MYSQL_ROOT_PASSWORD: &db_users_root_password 80jqn1uAWnoTjfPw
      MYSQL_USER: &db_users_user users_admin
      MYSQL_PASSWORD: &db_users_password 8t97tP366iPf7HnC     
    ports:
      - 33061:3306
    command: mysqld --innodb_file_per_table
  users:
    image: users
    build:
      context: ../users
      dockerfile: ./Dockerfile
    depends_on: 
      - users_db
    environment: 
      IS_DEBUG: *is_debug
      WEB_SERVER_PORT: 8080
      SERVICE_ADDRESS: &users_service_address http://users:8080
      DATABASE_SERVER_DATABASE: *db_users_database
      DATABASE_SERVER_HOST: *db_users_host
      DATABASE_SERVER_PORT: *db_users_port
      DATABASE_SERVER_USERNAME: *db_users_user
      DATABASE_SERVER_PASSWORD: *db_users_password
      <<: *security_password_factor
      <<: *security_jwt_key    
    ports:
      - 8082:8080
  developers:
    image: developers
    build:
      context: ../developers
      dockerfile: ./Dockerfile
    depends_on: 
      - developers_db
    environment: 
      IS_DEBUG: *is_debug
      WEB_SERVER_PORT: 8080
      SERVICE_ADDRESS: &dev_service_address http://developers:8080
      DATABASE_SERVER_DATABASE: *db_dev_database
      DATABASE_SERVER_HOST: *db_dev_host
      DATABASE_SERVER_PORT: *db_dev_port
      DATABASE_SERVER_USERNAME: *db_dev_user
      DATABASE_SERVER_PASSWORD: *db_dev_password
      <<: *security_password_factor
      <<: *security_jwt_key
    ports:
      - 8083:8080
  signin:
    image: signin
    build:
      context: ../signin
      dockerfile: ./Dockerfile
    depends_on: 
      - users
      - developers
    environment: 
      IS_DEBUG: *is_debug
      WEB_SERVER_PORT: 8080
      PROVIDERS_USER_SERVER_URI: *users_service_address
      PROVIDERS_DEVELOPER_SERVER_URI: *dev_service_address
      <<: *security_jwt_key
    ports:
      - 8081:8080